# Generated by Django 3.2.22 on 2024-07-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240707_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_email',
            new_name='default_contact_email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_full_name',
            new_name='default_contact_full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_phone_number',
            new_name='default_delivery_phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_delivery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
