# Generated by Django 3.2.22 on 2024-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecreator',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
