# Generated by Django 3.2.22 on 2024-07-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='delivery_phone_number',
        ),
    ]
