# Generated by Django 3.2.22 on 2024-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersendemail',
            name='letter_sent',
            field=models.BooleanField(default=False),
        ),
    ]
