# Generated by Django 3.2.22 on 2024-07-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_newslettersendemail_letter_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupportInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('enquiry_type', models.CharField(choices=[('order', 'Order Enquiry'), ('product', 'Product Enquiry'), ('returns', 'Returns'), ('complaints', 'Complaints'), ('work', 'Work With Us'), ('others', 'Others'), ('shipping', 'Shipping Inquiry'), ('payment', 'Payment Inquiry'), ('technical', 'Technical Support'), ('feedback', 'Feedback'), ('partnership', 'Partnership Inquiry')], max_length=50)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
