# Generated by Django 3.2.22 on 2024-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240617_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
