# Generated by Django 3.2.22 on 2024-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='creator_images'),
        ),
    ]
