# Generated by Django 3.2.22 on 2024-07-22 13:00

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, editable=False, null=True, upload_to='product_thumbnails'),
        ),
    ]
